version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: Ganesh
      POSTGRES_PASSWORD: Ganesh@123
      POSTGRES_DB: stoxportdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
